language: go
sudo: false

go:
  - 1.6
  - 1.7
  - master

install:
  - go get github.com/btcsuite/btcutil
  - go get github.com/metacoin/foundation

script:
  - test -z "$(go fmt ./...)"
  - go test

notifications:
  email: false
  slack:
    secure: IcJ7FAgl75NLbLFIFJ20KqSz6Y7G2cEIzocLZA6tnsYA4x5JxS8ZeHJaL6xidiRBYhG/0VtRwgX9ZerN60HNR3RsVnoTlUqkeVQ0ExW4cOVft5XXHz30o2I1QlJZ5MJAE3b47ptC7atZtsdf26rXl+7rqMyyW8dbR7YxcG/PHcSraoh7UlNSs2J8Dp8mztc0B54iuhcinoGzRPV5ug/ijR0w1u9q2Ink92ud77cALXkkRh1G4AoMlNL6b4HYqxKHFNlisK9c5ZZ6SrQv68sOg8e/yqBRUaOGKO0ZG9NUYn2Ent/oFXkuTfKy7TNNTX/AzVss4ECN/kioXD7zvsSlBlme/ef70Y/zFLAeV5Hy2gPcNU9BQ6rQ5/npODi9YtQXp/40kVIzzIcs4eSBiNRdO59b+XbOZVkbsbsxquMrTKwJL3YXPvrPi8u4Qqtsgrp1Pf8YqFG1cw1zL1vGHpDds7ZAJXp4wofs3iBYbLwQWILvs5DxnsOB3qegQA+cRk/h8nfrg1tpF1D5eVAiiy3E5EJatX8M2ErDPP7EFPe/noJCr9DprfSj/O/DufiOGzt78OE28wvNIWNWTDfZl/blo4vbZ8ZebnDPcud1Da/1fFi6j9Oxg4VHvFYsgN6x6i27HFeN+EkPxO9jec9o5gw9GyczFJhNCp59JIwhptwes4Y=